library(ggplot2)
library(plotly)
library(dplyr)

getwd()
setwd("../final")
data <- read.csv("./data/data.North.America.csv", stringsAsFactors = FALSE)
View(data)

data.North.America <- data %>% filter(region == 1)
data.Central.America <- data %>% filter(region == 2)
data.South.America <- data %>% filter(region == 3)
data.East.Asia <- data %>% filter(region == 4)
data.Southeast.Asia <- data %>% filter(region == 5)
data.South.Asia <- data %>% filter(region == 6)
data.Central.Asia <- data %>% filter(region == 7)
data.Western.Europe <- data %>% filter(region == 8)
data.Eastern.Europe <- data %>% filter(region == 9)
data.Middle.East.North.Africa <- data %>% filter(region == 10)
data.Sub.Africa <- data %>% filter(region == 11)
data.Australasia.Oceania <- data %>% filter(region == 12)

write.csv(data.North.America, "data/data.North.America.csv")
write.csv(data.Central.America, "data/data.Central.America.csv")
write.csv(data.South.America, "data/data.South.America.csv")
write.csv(data.East.Asia, "data/data.East.Asia.csv")
write.csv(data.Southeast.Asia, "data/data.Southeast.Asia.csv")
write.csv(data.South.Asia, "data/data.South.Asia.csv")
write.csv(data.Central.Asia, "data/data.Central.Asia.csv")
write.csv(data.Western.Europe, "data/data.Western.Europe.csv")
write.csv(data.Eastern.Europe, "data/data.Eastern.Europe.csv")
write.csv(data.Middle.East.North.Africa, "data/data.Middle.East.North.Africa.csv")
write.csv(data.Sub.Africa, "data/data.Sub.Africa.csv")
write.csv(data.Australasia.Oceania, "data/data.Australasia.Oceania.csv")
